# This compose file is for Coolify only. If you're looking for a complete
# docker setup, see the docker-compose.yml file with database and soketi.
# 
# documentation: https://github.com/rahulhaque/soketi-app-manager-filament
# slogan: Manage soketi websocket server and apps with ease.
# tags: soketi,app-manager,tools
# logo: svgs/soketi-app-manager-filament.svg
# port: 8080

services:
    soketi-app-manager-filament:
        build:
            dockerfile: Dockerfile
        image: soketi-app-manager-filament
        environment:
            - APP_URL=$SERVICE_FQDN_SOKETIAPPMANAGERFILAMENT
            - APP_KEY=$APP_KEY
            - DB_CONNECTION=$DB_CONNECTION
            - DB_HOST=$DB_HOST
            - DB_PORT=$DB_PORT
            - DB_DATABASE=$DB_DATABASE
            - DB_USERNAME=$DB_USERNAME
            - DB_PASSWORD=$DB_PASSWORD
            - REDIS_HOST=$REDIS_HOST
            - REDIS_PASSWORD=$REDIS_PASSWORD
            - REDIS_PORT=$REDIS_PORT
            - PUSHER_HOST=$PUSHER_HOST
            - PUSHER_PORT=$PUSHER_PORT
            - PUSHER_SCHEME=$PUSHER_SCHEME
            - PUSHER_APP_CLUSTER=$PUSHER_APP_CLUSTER
            - METRICS_HOST=$METRICS_HOST
