# This compose file is for Coolify only. If you're looking for a complete
# docker setup, see the docker-compose.yml file with database and soketi.
# 
# documentation: https://github.com/rahulhaque/soketi-app-manager-filament
# slogan: Manage soketi websocket server and apps with ease.
# tags: soketi,app-manager,tools
# logo: svgs/soketi-app-manager.svg
# port: 8080

services:
    soketi-app-manager:
        build:
            context: .
            dockerfile: Dockerfile.coolify
        image: soketi-app-manager
        depends_on:
            - mysql
            - redis
        environment:
            - PORT=8080
            - APP_URL=$SERVICE_FQDN_NGINX
            - APP_DEBUG=${APP_DEBUG:-false}
            - APP_KEY=$APP_KEY
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=${DB_DATABASE:-soketi_app_manager}
            - DB_USERNAME=${SERVICE_USER_MYSQL}
            - DB_PASSWORD=${SERVICE_PASSWORD_MYSQL}
            - REDIS_HOST=redis
            - REDIS_PASSWORD=${SERVICE_PASSWORD_REDIS}
            - PUSHER_HOST=soketi
            - PUSHER_PORT=6001
            - PUSHER_SCHEME=${PUSHER_SCHEME:-http}
            - PUSHER_APP_CLUSTER=$PUSHER_APP_CLUSTER
            - METRICS_HOST=${METRICS_HOST:-soketi:9601}
        healthcheck:
            test: ["CMD", "php-fpm-healthcheck"]
            start_period: 10s
            timeout: 5s
            interval: 5s
    mysql:
        image: 'mysql/mysql-server:8.0'
        environment:
            - MYSQL_DATABASE=${DB_DATABASE:-soketi_app_manager}
            - MYSQL_USER=${SERVICE_USER_MYSQL}
            - MYSQL_PASSWORD=${SERVICE_PASSWORD_MYSQL}
        volumes:
            - './docker/data/mysql:/var/lib/mysql'
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-u", "${SERVICE_USER_MYSQL}", "-p${SERVICE_PASSWORD_MYSQL}"]
            retries: 3
            timeout: 5s
            interval: 5s
    redis:
        image: 'redis:7.2-alpine'
        command: redis-server --save 60 1 --loglevel warning --requirepass "${SERVICE_PASSWORD_REDIS}"
        volumes:
            - './docker/data/redis:/data'
    soketi:
        image: 'quay.io/soketi/soketi:latest-16-alpine'
        environment:
            - SOKETI_DEBUG=${SOKETI_DEBUG:-false}
            - SOKETI_METRICS_ENABLED=${SOKETI_METRICS_ENABLED:-true}
            - SOKETI_WEBHOOKS_BATCHING=${SOKETI_WEBHOOKS_BATCHING:-true}
            - SOKETI_APP_MANAGER_CACHE_ENABLED=${SOKETI_APP_MANAGER_CACHE_ENABLED:-true}
            - SOKETI_DB_POOLING_ENABLED=${SOKETI_DB_POOLING_ENABLED:-true}
            - SOKETI_QUEUE_DRIVER=redis
            - SOKETI_CACHE_DRIVER=redis
            - SOKETI_RATE_LIMITER_DRIVER=redis
            - SOKETI_DB_MYSQL_HOST=mysql
            - SOKETI_DB_MYSQL_PORT=3306
            - SOKETI_DB_MYSQL_USERNAME=${SERVICE_USER_MYSQL}
            - SOKETI_DB_MYSQL_PASSWORD=${SERVICE_PASSWORD_MYSQL}
            - SOKETI_DB_MYSQL_DATABASE=${DB_DATABASE:-soketi_app_manager}
            - SOKETI_APP_MANAGER_DRIVER=mysql
            - SOKETI_APP_MANAGER_MYSQL_TABLE=applications
            - SOKETI_APP_MANAGER_MYSQL_USE_V2=${SOKETI_APP_MANAGER_MYSQL_USE_V2:-true} # Change this if you're having issue connecting to MySQL
            - SOKETI_APP_MANAGER_CACHE_TTL=3600
            - SOKETI_DB_REDIS_HOST=redis
            - SOKETI_DB_REDIS_PASSWORD=${SERVICE_PASSWORD_REDIS}
        depends_on:
            - mysql
            - redis
        healthcheck:
            test: ["CMD-SHELL", "bash -c ':> /dev/tcp/127.0.0.1/6001' || exit 1"]
            interval: 5s
            timeout: 20s
            retries: 3
